### ISSUE TITLE
Manual scrobbling

### ISSUE THREAD

**Issue by lorefield** [kawaiiDango/pano-scrobbler#459] opened 2024-05-01 22:27 UTC
Are there plans to implement some form of manual scrobbling, like sites like Open Scrobbler allow you to do? For people that listen to cd's and vinyl it could be convenient to search something through Pano Scrobbler's interface - which works well! - and then to be able to press a  'scrobble this album/track' (with options to date the scrobble).

**Comment by kawaiiDango** [comment] 2024-05-02 07:22
Duplicate of https://github.com/kawaiiDango/pano-scrobbler/issues/438

**Closed** 2024-05-02 07:22 UTC
Labels: enhancement
