### ISSUE TITLE
Battery drain from recent update

### ISSUE THREAD

**Issue by skypeias** [kawaiiDango/pano-scrobbler#507] opened 2024-10-19 10:18 UTC
I just noticed this entire month that Pano Scrobbler would just drain my battery in the background, especially when not in use. the hotfix rn is to force close the app but the battery drain does come back after some time

**Comment by kawaiiDango** [comment] 2024-10-19 19:12
Duplicate of #496

**Closed** 2024-10-19 19:23 UTC
Labels: bug
