### ISSUE TITLE
Pleroma sign-in failing, "Invalid Username/Password"

### ISSUE THREAD

**Issue by AtlasC0R3** [kawaiiDango/pano-scrobbler#475] opened 2024-07-05 19:14 UTC
**Describe the bug**
Upon tapping the option to sign into Pleroma from Pano Scrobbler, and entering the URL of the instance as Server URL (including `https://`), no sign-in method is successful. I have tried using my normal username, the full username (at user at instance), the email address I signed up with, nothing works. It always returns "Invalid Username/Password".
This feature also hasn't worked on a self-hosted instance, throwing the exact same error.

**Steps to Reproduce**
1. Open Pano Scrobbler
2. Sign into Pleroma
3. Enter instance as "Server URL" (in my case, `https://pl.starnix.network`)
4. Sign in normally (username, password)
5. Something fails

**App version**
3.35, installed from F-Droid I believe.

**Additional info**
![Screenshot_20240705-151231](https://github.com/kawaiiDango/pano-scrobbler/assets/39468657/5de1025d-ac98-4799-9ca4-924fe1c90c44)

**Comment by kawaiiDango** [comment] 2024-07-05 23:59
I found the cause, this will be fixed

**Closed** 2024-08-01 09:37 UTC
Labels: bug
